### ISSUE TITLE
No instance nor default method for class operation Data.Vector.Generic.Mutable.Base.basicInitialize

### ISSUE THREAD

**Issue by unhammer** [kawu/nerf#48]
$ cat nerf.input 
    This was the <organization>Church of the <deity>Flying Spaghetti Monster</deity></organization> that later on was renamed to <organization>Congregation of the <deity>Monster</deity></organization> in 2001
    $ .cabal-sandbox/bin/nerf train nerf.input -o model.bin                                                                                                        
    
    [0] acc = #
    
    [30] acc = #
    
    Saving model in model.bin...
    $ .cabal-sandbox/bin/nerf ner model.bin < nerf.input                                                                                      
    nerf: Data/CRF/Chain1/Model.hs:44:1-71: No instance nor default method for class operation Data.Vector.Generic.Mutable.Base.basicInitialize

**Comment by kawu** [comment]
I completely overlooked this issue, sorry.  Anyway, I moved to `stack` recently and the problem (which I cannot reproduce) should not occur anymore.

```
$ cat nerf.nes 
This was the <organization>Church of the <deity>Flying Spaghetti Monster</deity></organization> that later on was renamed to <organization>Congregation of the <deity>Monster</deity></organization> in 2001
$ nerf train nerf.nes -e nerf.nes -o model.bin

[0] acc = 0.14285714285714285

[30] acc = 1.0

Saving model in model.bin...
$ cat nerf.txt 
This was the Church of the Flying Spaghetti Monster that later on was renamed to Congregation of the Monster in 2001
$ nerf ner -i model.bin < nerf.txt
This was the <organization>Church of the <deity>Flying Spaghetti Monster</deity></organization> that later on was renamed to <organization>Congregation of the <deity>Monster</deity></organization> in 2001
```
